### ISSUE TITLE
Improving performance: aka To-Do for Performance

### ISSUE THREAD

**Issue by dalisoft** [veltman/flubber#91]
Here i wanna to make this project as fast as possible, for creating plug-in for my project.

To-Do's:
- [x] 1. Converting Curves to Lines, solution [here](https://github.com/mattdesl/adaptive-bezier-curve)
- [x] 2. Point-A-Long replacement to direct interpolation (improves by 5-15% performance)
- [x] 3. distance replacement to direct `Math.sqrt` (improves 5%)
- [ ] 4. Implementing the change of `index`
- [x] 5. Implementing the config for disabling topology/split into parts, as this costs at perf

Total performance improvements: `1` (5-50%) + `2` (5-15%) + `3` (5%) = 15%-70% improvements

And some others, that may i change in future

**Comment by veltman** [comment]
Feel free to submit a PR!
